# Generated by Django 3.1 on 2020-08-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='depart',
            new_name='color',
        ),
    ]
