# Generated by Django 3.1 on 2020-08-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200822_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color2',
            field=models.CharField(default='blue', max_length=200),
        ),
    ]
